# Generated by Django 5.2.7 on 2025-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('employee_type', models.CharField(choices=[('tailor', 'Оёдолчин'), ('cutter', 'Эсгүүрчин'), ('trouser_maker', 'Өмдний оёдолчин')], max_length=20, verbose_name='Албан тушаал')),
                ('specialties', models.JSONField(default=list, verbose_name='Мэргэшсэн чиглэл')),
                ('phone', models.CharField(max_length=20, verbose_name='Утасны дугаар')),
                ('experience_years', models.IntegerField(verbose_name='Туршлага (жил)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сүүлд шинэчлэгдсэн огноо')),
            ],
            options={
                'verbose_name': 'Ажилтан',
                'verbose_name_plural': 'Ажилтнууд',
                'ordering': ['name'],
            },
        ),
    ]
