# Generated by Django 5.2.7 on 2025-10-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('cutter', 'Эсгүүрчин'), ('shirt_cutter', 'Цамцны эсгүүрчин'), ('jacket_sewer', 'Пиджак оёдолчин'), ('trouser_sewer', 'Өмдний оёдолчин'), ('shirt_sewer', 'Цамцны оёдолчин')], max_length=20, verbose_name='Албан тушаал'),
        ),
    ]
