# Generated by Django 5.2.7 on 2025-10-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_employee_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Ажилтан', 'verbose_name_plural': 'Ажилтнууд'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialties',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Нэр'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Овог'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Утасны дугаар'),
        ),
    ]
