# Generated by Django 4.2.7 on 2025-10-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_login_access',
            field=models.BooleanField(default=False, verbose_name='Нэвтрэх эрхтэй'),
        ),
    ]
