# Generated by Django 4.2.7 on 2025-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_has_login_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_password',
            field=models.CharField(blank=True, help_text='Хэрэв хоосон байвал автоматаар үүснэ', max_length=128, null=True, verbose_name='Нууц үг'),
        ),
    ]
