# Generated by Django 4.2.7 on 2025-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('manager', 'Менежер'), ('cutter', 'Эсгүүрчин'), ('shirt_cutter', 'Цамцны эсгүүрчин'), ('jacket_sewer', 'Пиджак оёдолчин'), ('trouser_sewer', 'Өмдний оёдолчин'), ('shirt_sewer', 'Цамцны оёдолчин')], max_length=20, verbose_name='Албан тушаал'),
        ),
    ]
