# Generated by Django 4.2.7 on 2025-10-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Овог'),
        ),
    ]
