# Generated by Django 5.2.7 on 2025-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Материалын нэр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нэгжийн үнэ')),
                ('unit', models.CharField(default='метр', max_length=20, verbose_name='Хэмжих нэгж')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Үлдэгдэл')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нийлүүлэгч')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сүүлд шинэчлэгдсэн огноо')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалууд',
                'ordering': ['name'],
            },
        ),
    ]
