# Generated by Django 5.2.7 on 2025-10-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тайлангийн гарчиг')),
                ('report_type', models.CharField(choices=[('orders_summary', 'Захиалгын хураангуй'), ('employee_performance', 'Ажилтны гүйцэтгэл'), ('customer_analysis', 'Үйлчлүүлэгчийн шинжилгээ'), ('material_usage', 'Материалын хэрэглээ'), ('financial_summary', 'Санхүүгийн хураангуй')], max_length=50, verbose_name='Тайлангийн төрөл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('data', models.JSONField(default=dict, verbose_name='Тайлангийн өгөгдөл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('period_start', models.DateField(verbose_name='Хугацааны эхлэл')),
                ('period_end', models.DateField(verbose_name='Хугацааны төгсгөл')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн хүн')),
            ],
            options={
                'verbose_name': 'Тайлан',
                'verbose_name_plural': 'Тайлангууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
