# Generated by Django 4.2.7 on 2025-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Түлхүүр')),
                ('value', models.CharField(max_length=500, verbose_name='Утга')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тайлбар')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сүүлд шинэчлэгдсэн огноо')),
            ],
            options={
                'verbose_name': 'Системийн тохиргоо',
                'verbose_name_plural': 'Системийн тохиргоонууд',
                'ordering': ['key'],
            },
        ),
    ]
