# Generated by Django 5.2.7 on 2025-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('last_name', models.CharField(max_length=100, verbose_name='Овог')),
                ('phone', models.CharField(max_length=20, verbose_name='Утасны дугаар')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имэйл')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Хаяг')),
                ('customer_type', models.CharField(choices=[('regular', 'Энгийн үйлчлүүлэгч'), ('vip', 'VIP үйлчлүүлэгч')], default='regular', max_length=10, verbose_name='Үйлчлүүлэгчийн төрөл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сүүлд шинэчлэгдсэн огноо')),
            ],
            options={
                'verbose_name': 'Үйлчлүүлэгч',
                'verbose_name_plural': 'Үйлчлүүлэгчид',
                'ordering': ['-created_at'],
            },
        ),
    ]
