# Generated by Django 4.2.7 on 2025-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(choices=[('ulaanbaatar', 'Улаанбаатар'), ('arkhangai', 'Архангай'), ('bayankhongor', 'Баянхонгор'), ('bayanolgii', 'Баян-Өлгий'), ('bulgan', 'Булган'), ('govialtai', 'Говь-Алтай'), ('govisumber', 'Говьсүмбэр'), ('darkhan', 'Дархан-Уул'), ('dornod', 'Дорнод'), ('dornogovi', 'Дорноговь'), ('dundgovi', 'Дундговь'), ('zavkhan', 'Завхан'), ('orhon', 'Орхон'), ('ovorkhangai', 'Өвөрхангай'), ('omnogovi', 'Өмноговь'), ('suhebaatar', 'Сүхбаатар'), ('selenge', 'Сэлэнгэ'), ('tov', 'Төв'), ('uvs', 'Увс'), ('hovsgol', 'Хөвсгөл'), ('khovd', 'Ховд'), ('khentii', 'Хэнтий')], default='ulaanbaatar', max_length=20, verbose_name='Аймаг'),
        ),
    ]
