# Generated by Django 5.2.7 on 2025-10-18 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Захиалгын дугаар')),
                ('item_type', models.CharField(max_length=100, verbose_name='Хувцасны төрөл')),
                ('material_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материалын тайлбар')),
                ('measurements', models.JSONField(default=dict, verbose_name='Хэмжээ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Нийт дүн')),
                ('start_date', models.DateField(verbose_name='Эхлэх огноо')),
                ('due_date', models.DateField(verbose_name='Дуусах огноо')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дууссан огноо')),
                ('current_status', models.CharField(choices=[('order_placed', 'Захиалга өгсөн'), ('material_arrived', 'Материал ирсэн'), ('cutter_cutting', 'Эсгүүрчин эсгэсэн'), ('customer_first_fitting', 'Үйлчлүүлэгч 1-р хэмжээ'), ('tailor_first_completion', 'Эсгүүрчин 1-р хэмжээ миллэсэн'), ('seamstress_second_prep', 'Оёдолчин 2-р хэмжээ бэлдсэн'), ('customer_second_fitting', 'Үйлчлүүлэгч 2-р хэмжээ'), ('tailor_second_completion', 'Эсгүүрчин 2-р хэмжээ миллэсэн'), ('seamstress_finished', 'Оёдолчин оёж дууссан')], default='order_placed', max_length=50, verbose_name='Одоогийн статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
                ('is_rated', models.BooleanField(default=False, verbose_name='Үнэлгээ өгсөн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сүүлд шинэчлэгдсэн огноо')),
                ('assigned_cutter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutter_orders', to='employees.employee', verbose_name='Эсгүүрчин')),
                ('assigned_tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailor_orders', to='employees.employee', verbose_name='Оёдолчин')),
                ('assigned_trouser_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trouser_maker_orders', to='employees.employee', verbose_name='Өмдний оёдолчин')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Үйлчлүүлэгч')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Захиалга',
                'verbose_name_plural': 'Захиалга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(verbose_name='Ерөнхий үнэлгээ')),
                ('quality_rating', models.IntegerField(verbose_name='Чанарын үнэлгээ')),
                ('service_rating', models.IntegerField(verbose_name='Үйлчилгээний үнэлгээ')),
                ('timing_rating', models.IntegerField(verbose_name='Хугацааны үнэлгээ')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Сэтгэгдэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үнэлгээ өгсөн огноо')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.order', verbose_name='Захиалга')),
            ],
            options={
                'verbose_name': 'Захиалгын үнэлгээ',
                'verbose_name_plural': 'Захиалгын үнэлгээнүүд',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(max_length=50, verbose_name='Алхамын төрөл')),
                ('title', models.CharField(max_length=100, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('in_progress', 'Хийгдэж байгаа'), ('completed', 'Дууссан')], default='pending', max_length=20, verbose_name='Статус')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дууссан огноо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сүүлд шинэчлэгдсэн огноо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='orders.order', verbose_name='Захиалга')),
            ],
            options={
                'verbose_name': 'Үйл явцын алхам',
                'verbose_name_plural': 'Үйл явцын алхамууд',
                'ordering': ['created_at'],
            },
        ),
    ]
