# Generated by Django 4.2.7 on 2025-10-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Захиалга өгсөн'), ('material_arrived', 'Материал ирсэн'), ('cutter_cutting', 'Эсгүүрчин эсгэсэн'), ('customer_first_fitting', 'Үйлчлүүлэгч 1-р хэмжээ'), ('tailor_first_completion', 'Эсгүүрчин 1-р хэмжээ миллэсэн'), ('seamstress_second_prep', 'Оёдолчин 2-р хэмжээ бэлдсэн'), ('customer_second_fitting', 'Үйлчлүүлэгч 2-р хэмжээ'), ('tailor_second_completion', 'Эсгүүрчин 2-р хэмжээ миллэсэн'), ('seamstress_finished', 'Оёдолчин оёж дууссан')], max_length=50, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дууссан огноо')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Дуусгасан хүн')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Захиалга')),
            ],
            options={
                'verbose_name': 'Захиалгын статусын түүх',
                'verbose_name_plural': 'Захиалгын статусын түүх',
                'ordering': ['-completed_at'],
            },
        ),
    ]
