# Generated by Django 4.2.7 on 2025-10-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_back',
            field=models.ImageField(blank=True, null=True, upload_to='order_designs/back/', verbose_name='Хойд талын загвар'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_front',
            field=models.ImageField(blank=True, null=True, upload_to='order_designs/front/', verbose_name='Урд талын загвар'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_reference',
            field=models.ImageField(blank=True, null=True, upload_to='order_designs/reference/', verbose_name='Жишээ загвар'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_side',
            field=models.ImageField(blank=True, null=True, upload_to='order_designs/side/', verbose_name='Хажуугийн загвар'),
        ),
    ]
