# Generated by Django 4.2.7 on 2025-10-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_design_back_order_design_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_type',
            field=models.CharField(choices=[('men_suit', 'Эрэгтэй костюм'), ('women_suit', 'Эмэгтэй костюм'), ('wedding_dress', 'Хуримын даашинз'), ('formal_dress', 'Албан ёсны даашинз'), ('casual_shirt', 'Энгийн цамц'), ('trousers', 'Өмд'), ('jacket', 'Пиджак'), ('vest', 'Жилэт'), ('coat', 'Пальто'), ('repair', 'Хувцас засвар'), ('other', 'Бусад')], max_length=50, verbose_name='Хувцасны төрөл'),
        ),
    ]
