# Generated by Django 4.2.7 on 2025-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
        migrations.AddField(
            model_name='order',
            name='material_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материалын код'),
        ),
    ]
