# Generated by Django 4.2.7 on 2025-10-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_measurements_order_material_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material_description',
        ),
    ]
