# Generated by Django 4.2.7 on 2025-10-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_login_password'),
        ('orders', '0006_remove_order_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5', verbose_name='Үнэлгээ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Сэтгэгдэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үнэлгээ өгсөн огноо')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='employees.employee', verbose_name='Ажилтан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ratings', to='orders.order', verbose_name='Захиалга')),
            ],
            options={
                'verbose_name': 'Ажилтны үнэлгээ',
                'verbose_name_plural': 'Ажилтнуудын үнэлгээнүүд',
                'unique_together': {('order', 'employee')},
            },
        ),
    ]
