# Generated by Django 5.2.7 on 2025-11-13 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_employeerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Урьдчилгаа дүн'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('order_placed', 'Захиалга өгсөн'), ('material_arrived', 'Материал ирсэн'), ('cutter_cutting', 'Эсгүүрчин эсгэсэн'), ('customer_first_fitting', 'Үйлчлүүлэгч 1-р хэмжээ өмссөн'), ('tailor_first_completion', 'Эсгүүрчин 1-р хэмжээ миллэсэн'), ('seamstress_second_prep', 'Оёдолчин 2-р хэмжээ бэлдсэн'), ('customer_second_fitting', 'Үйлчлүүлэгч 2-р хэмжээ өмссөн'), ('tailor_second_completion', 'Эсгүүрчин 2-р хэмжээ миллэсэн'), ('seamstress_finished', 'Оёдолчин оёж дууссан')], default='order_placed', max_length=50, verbose_name='Одоогийн статус'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Захиалга өгсөн'), ('material_arrived', 'Материал ирсэн'), ('cutter_cutting', 'Эсгүүрчин эсгэсэн'), ('customer_first_fitting', 'Үйлчлүүлэгч 1-р хэмжээ өмссөн'), ('tailor_first_completion', 'Эсгүүрчин 1-р хэмжээ миллэсэн'), ('seamstress_second_prep', 'Оёдолчин 2-р хэмжээ бэлдсэн'), ('customer_second_fitting', 'Үйлчлүүлэгч 2-р хэмжээ өмссөн'), ('tailor_second_completion', 'Эсгүүрчин 2-р хэмжээ миллэсэн'), ('seamstress_finished', 'Оёдолчин оёж дууссан')], max_length=50, verbose_name='Статус'),
        ),
    ]
